apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: portfolio-website
        image: docker.io/sovu/portfolio-website:latest
        ports:
        - containerPort: 8080
